[build]

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    content-type="application/jrd+json; charset=UTF-8"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    content-type="text/xml; charset=UTF-8"

[[headers]]
  for="/racing_data.json"
  [headers.values]
    access-control-allow-origin = "*"   

[[headers]]
  for="/racing_data_cat.json"
  [headers.values]
    access-control-allow-origin = "*"   
